Update table view with the code of spree 3-1-stable
theam/spree-product-assembly pull request #1
Opened 2017-10-05 11:27 UTC by itrion

The code in this defaced view was outdated and wasn't including the `special_instructions` attribute in order

2017-10-05 12:48 UTC, gonzalogarciajaubert commented on app/views/spree/admin/orders/_stock_contents.html.erb
> +  <% if rate = shipment.selected_shipping_rate %>
en ruby era `=` o `==`?

2017-10-05 12:51 UTC, gonzalogarciajaubert requested changes
creo que lo del `igual` habria que cambiarlo, de resto genial!

2017-10-05 13:40 UTC, alvaroloes commented on app/views/spree/admin/orders/_stock_contents.html.erb
> +  <% if rate = shipment.selected_shipping_rate %>
Es '==' !

2017-10-05 13:45 UTC, alvaroloes requested changes
Coincido en que sería mejor no usar la asinación en un if (puede confundir). De resto LGTM

2017-10-06 08:22 UTC, itrion commented on app/views/spree/admin/orders/_stock_contents.html.erb
> +  <% if rate = shipment.selected_shipping_rate %>
Done 👍

2017-10-09 11:38 UTC, gonzalogarciajaubert approved these changes
💯

2017-10-09 11:45 UTC, alvaroloes approved these changes
Gracias!

2017-10-09 11:46 UTC, merged